apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: iac-verifier-webhook
  annotations:
    cert-manager.io/inject-ca-from: default/iac-webhook-cert
webhooks:
  - name: iac-verifier.default.svc
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["configmaps"]
        scope: "Namespaced"
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values: ["kube-system", "kube-public", "kube-node-lease"]
    objectSelector:
      matchLabels:
        iac-verifier/scan: "true"
    clientConfig:
      service:
        name: iac-webhook-service
        namespace: default
        path: "/validate"
        port: 443
      caBundle: ""
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 10
    failurePolicy: Fail
