apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: iac-verifier-webhook
webhooks:
  - name: iac-verifier.default.svc
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["configmaps"]
        scope: "Namespaced"
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values: ["kube-system", "kube-public", "kube-node-lease"]
    objectSelector:
      matchLabels:
        iac-verifier/scan: "true"
    clientConfig:
      service:
        name: iac-webhook-service
        namespace: default
        path: "/validate"
        port: 443
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMwekNDQWJ1Z0F3SUJBZ0lVYUxJVjc4UHl2YjNNVXJYbndmUW9aRUg5V3Zzd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0dURVhNQlVHQTFVRUF3d09TV0ZESUZkbFltaHZiMnNnUTBFd0hoY05Nall3T1RBek1EYzFORE00V2hjTgpNamN3T1RBek1EYzFORE00V2pBWk1SY3dGUVlEVlFRRERBNUpZVU1nVjJWaWFHOXZheUJEUVRDQ0FTSXdEUVlKCktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQUxqb29EclRGTFBuUFB0aU1LU05UVE9peFFuZDBodGsKeTdWa0ZOdHhSRFYxcVJMbk5WMGJDNzJNaXVUQzRyVk1LR3dJVktqdng1d3c0MzMyajFnZW5ldGVPa2MzWng0Vwoxd1dyaFFtdGVHVGo0VFVxQlNzWXVMdjZqZHpwWHY4bEgydS9tNkFMV0R2MWNVVytXSDRFaXpFK1NCQVpmNy94CkdLU0N3aERENFVRK2xoUjJOQjNKOTF5ck8vQm0yNW8wbnBXL3FNbTNKWXVqandlOU1rUlhsMGZnWDcrelVlWTAKb0xNZzdJdTZTQ3NDQVhkdllpWDVPQmdnazFGTlgxRlIxTndCU2Z3WGZUY0NYenZqeGs5VXBBdnZxVGcrTEc4NgpkOWdJNDc2WTRvSWZ3U1JIU2c1Tlk5QWIrK3dpTi9BSUh3M3ZxZzBnbVgxQ211VVdxLzZGTGpFQ0F3RUFBYU1UCk1CRXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFIOGVIUVlNMHJUdUYKWkMrSmtGeHAvY2JDSHJGbGFJNkJQb28xSTVMS21TOFdYblJtbjJYckIwc3ZRZnkyY3R4bUo0RjJ4REFtOVp5bQpDc2dPdUxZaDFTSFFwRDBTRHRGbTlESUpIWXcrQUM3bUlaTHlFVUFYeXZ3aCt3NTZheWw2TURETi9ZTDBCUHVkCmtXaDVpUU9CVFFQL2Joai95bGZHYzZ4M3N6SitmUDI4akczUWVjK3BHVDZJL240NVZ0ZjNVOHVaODBySXloMnIKbXZzMWNyUC9Gbm4yMVdFbFFRWXkzNGJGKzQrN05iK010WG8yQWI3bGw0THJXSnBqUysxZHBRRDV3ZGMvQURTeQpMdzQrNUp5MklUaUdhc25FdGQ5QWFYRkJqMkQ3U2VsVkZ4NCtZclRUaVljcFBmTG5XeHI4OHltcDVXQzA1eDhxCkxMZ0laSm93U2c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 10
    failurePolicy: Fail
